pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.parchmentmc.org" }
        gradlePluginPortal()
        mavenLocal()
    }
}

include("common")
include("neoforge")

if (!gradle.startParameter.projectProperties.containsKey("forgeBuildOnly")) {
    include("common-mojmap")
    include("fabric")
    include("cclayer")
    include("tclayer")
}

rootProject.name = "accessories"
